name: gencare_service

services:
  backend:
    container_name: gencare_backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - API/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=GenCare;Username=admin;Password=12345

  database:
    container_name: gencare_database
    image: postgres:17
    restart: always
    volumes:
      - gencare_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - API/.env
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=GenCare
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d GenCare"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  gencare_postgres_data:
