name: backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths:
      - "backend/**"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend
      - name: Build the app
        run: dotnet build --no-restore
        working-directory: backend
      - name: Run tests
        run: dotnet test --no-build
        working-directory: backend
      - name: Trigger deployment
        run: echo "Deploying..."
        working-directory: backend
