name: backend

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    types: [synchronize, opened, reopened, edited]
    paths:
      - "backend/**"

env:
  SKIP_DEPLOYMENT: ${{ contains(github.event.head_commit.message, '#skip') }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend
      - name: Build the app
        run: dotnet build --no-restore
        working-directory: backend
      - name: Run tests
        run: dotnet test --no-build
        working-directory: backend
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT == 'false' }}
        run: echo "Deploying..."
        working-directory: backend
