name: frontend
permissions:
  contents: read

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    paths:
      - "frontend/**"

env:
  SKIP_DEPLOYMENT: ${{ contains(github.event.head_commit.message, '#skip') }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Style check
        run: npm run lint
        working-directory: frontend

      - name: Building the app
        run: npm run build
        working-directory: frontend

      - name: Deploying the app
        uses: amondnet/vercel-action@v25 #deploy
        if: ${{ github.event_name == 'pull_request' && env.SKIP_DEPLOYMENT == 'false' }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
